"""empty message

Revision ID: 1ce4507942e4
Revises: e2924442d86
Create Date: 2014-07-21 16:32:03.288855

"""

# revision identifiers, used by Alembic.
revision = '1ce4507942e4'
down_revision = 'e2924442d86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('max_amount', sa.Numeric(precision=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'max_amount')
    ### end Alembic commands ###
