"""empty message

Revision ID: 1f9efabc486
Revises: 536b2b236ebc
Create Date: 2014-07-22 17:50:33.482520

"""

# revision identifiers, used by Alembic.
revision = '1f9efabc486'
down_revision = '3e78457e77a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_code', sa.Column('mercadopago_collection_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_code', 'mercadopago_collection_id')
    ### end Alembic commands ###
