"""empty message

Revision ID: 234152e69e15
Revises: 1ce4507942e4
Create Date: 2014-07-21 16:33:10.538975

"""

# revision identifiers, used by Alembic.
revision = '234152e69e15'
down_revision = '1ce4507942e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_pago_payment_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercado_pago_payment_preference')
    ### end Alembic commands ###
