"""empty message

Revision ID: 245ee6fe3086
Revises: 40b99fc576ef
Create Date: 2014-07-23 15:14:48.135138

"""

# revision identifiers, used by Alembic.
revision = '245ee6fe3086'
down_revision = '40b99fc576ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'max_downloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'max_downloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
