"""empty message

Revision ID: 3c42990ec50d
Revises: b94ac190bbc
Create Date: 2014-10-31 18:48:18.875458

"""

# revision identifiers, used by Alembic.
revision = '3c42990ec50d'
down_revision = 'b94ac190bbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('extra_head_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'extra_head_html')
    ### end Alembic commands ###
