"""empty message

Revision ID: 3e78457e77a9
Revises: 55fce4de1348
Create Date: 2014-07-22 12:56:06.798019

"""

# revision identifiers, used by Alembic.
revision = '3e78457e77a9'
down_revision = '55fce4de1348'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mercado_pago_payment_preference', sa.Column('payment_preference_id', sa.String(length=50), nullable=True))
    op.add_column('project', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'description')
    op.drop_column('mercado_pago_payment_preference', 'payment_preference_id')
    ### end Alembic commands ###
