"""empty message

Revision ID: 536b2b236ebc
Revises: 3e78457e77a9
Create Date: 2014-07-22 17:48:10.554824

"""

# revision identifiers, used by Alembic.
revision = '536b2b236ebc'
down_revision = '3e78457e77a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('project_code_idx', 'download_code', ['project_id', 'code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_code_idx', table_name='download_code')
    ### end Alembic commands ###
