"""empty message

Revision ID: 572453d72309
Revises: 9c5d5b43840
Create Date: 2014-07-23 11:01:11.602208

"""

# revision identifiers, used by Alembic.
revision = '572453d72309'
down_revision = '9c5d5b43840'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'email_sent_at')
    ### end Alembic commands ###
