"""empty message

Revision ID: 9c5d5b43840
Revises: 2b5d4e944359
Create Date: 2014-07-22 19:39:23.709714

"""

# revision identifiers, used by Alembic.
revision = '9c5d5b43840'
down_revision = '2b5d4e944359'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('project_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'project_id')
    ### end Alembic commands ###
